name: CI workflow

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev

      - name: Build
        run: zig build -Doptimize=ReleaseFast

      - name: Archive production artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ./zig-out/bin/gwin

  ci-pkgbuild:
    needs: ci
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - name: Install git
        run: pacman -Syu --noconfirm git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup non-root build user
        run: |
          useradd -m -G wheel builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          chown -R builder:builder $GITHUB_WORKSPACE

      - name: Bootstrap yay-bin
        run: |
          su - builder -c "git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin"
          su - builder -c "cd /tmp/yay-bin && makepkg -si --noconfirm"

      - name: Build local PKGBUILD
        run: |
          su - builder -c "cd $GITHUB_WORKSPACE && yay -Bi --noconfirm ."

  cd-pkgbuild-check:
    needs: ci-pkgbuild
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for PKGBUILD changes
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            pkgbuild:
              - 'PKGBUILD'

  cd-pkgbuild:
    needs: cd-pkgbuild-check
    if: ${{ github.ref == 'refs/heads/main' && needs.cd-pkgbuild-check.outputs.pkgbuild == 'true' && !contains(github.event.head_commit.message, '[skip-cd]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for PKGBUILD changes
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            pkgbuild:
              - 'PKGBUILD'

      - name: Publish AUR package
        if: steps.filter.outputs.pkgbuild == 'true'
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: shell-utils-git
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update AUR package"
          ssh_keyscan_types: rsa,ecdsa,ed25519

  cd-apt:
    needs: [ci, ci-pkgbuild]
    if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-cd]') && github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ruby ruby-dev rubygems build-essential
          sudo gem install fpm

      - name: Package it using fpm
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          DYNAMIC_VERSION="1.0.0+git${COMMIT_COUNT}.${COMMIT_HASH}"

          mkdir -p staging-root/usr/bin; cp ./gwin staging-root/usr/bin/
          mkdir -p staging-root/usr/share/zsh/vendor-completions; cp ./completions/zsh/_gwin staging-root/usr/share/zsh/vendor-completions/

          fpm -s dir -t deb \
            -n gwin \
            -v $DYNAMIC_VERSION \
            -a amd64 \
            --maintainer "Vinicius Mayrink <vncsmyrnk@gmail.com>" \
            --description "A \"Run or raise\" CLI tool for Wayland GNOME." \
            -d "libglib2.0-0" \
            -d "gnome-shell" \
            --license "GPL-3.0" \
            --url "https://github.com/vncsmyrnk/gwin" \
            -C staging-root .

      - name: Upload to Gemfury
        run: |
          DEB_FILE=$(find . -name '*.deb' -type f | head -n 1)
          curl -F package=@$DEB_FILE https://${{ secrets.GEMFURY_PUSH_TOKEN }}@push.fury.io/vncsmyrnk
